In [1]:
from pyspark.sql import *
spark=SparkSession.builder.appName("ap1").getOrCreate()

In [2]:
df=spark.read.csv("/FileStore/tables/walmart_stock.csv", inferSchema=True, header=True)

In [3]:
df.show(5)

In [4]:
df.columns

In [5]:
df.printSchema()

In [6]:
df.head(5)

In [7]:
df.describe().show()

In [8]:
from pyspark.sql.types import StructType,StructField

In [9]:
from pyspark.sql.types import *
schema=StructType([StructField('date', DateType(), True), StructField('open', DateType(), True), StructField('low', StringType(), True), StructField('close', DoubleType(), True), StructField('volume', IntegerType(), True)])

In [10]:
df1=df.schema

In [11]:
df.printSchema

In [13]:
df3.show()

In [14]:
df2.show()

In [15]:
df.withColumn("HV Ratio",df['high']/df['Volume']).show()

In [16]:
df.createOrReplaceTempView("walmart")

In [17]:
mh=spark.sql("select Date from walmart where high=(select max(high) from walmart)")

In [18]:
mh.show()

In [19]:
mh1=spark.sql("select avg(close) from walmart")

In [20]:
mh1.show()

In [21]:
mh2=spark.sql("select max(volume),min(volume) from walmart")

In [22]:
mh2.show()

In [23]:
mh3=spark.sql("select count(*) as no_days from walmart where close<=60")

In [24]:
mh3.show()

In [25]:
mh4=spark.sql("select (select count(*) from walmart where high>80)*100/count(*) as days from walmart")

In [26]:
mh4.show()

In [27]:
df.corr("High","Volume")

In [28]:
from pyspark.sql.functions import year
mh5=df.select(year(df['date']).alias("Year"),'high')

In [29]:
mh5.head(2)

In [30]:
mh6=mh5.groupBy("Year")

In [31]:
mh6.max('high').show()

In [32]:
from pyspark.sql.functions import month
mh7=df.select(month('date').alias('Month'),'close')

In [33]:
mh7.show()

In [34]:
mh8=mh7.groupBy('Month')

In [35]:
mh8.avg('close').show()